// Auto-generated code. Don't modify.

export const formularioBody: string;
export const formType: string;
export const helperText: string;
export const formBody: string;
export const formHead: string;
export const inputField: string;
export const col: string;
export const sentence: string;
export const dinamycTable: string;
export const dotted: string;
export const dottValid: string;
export const dottInvalid: string;
export const errorInline: string;
export const xelectDisabled: string;
export const btnPhoto: string;
export const btnPhot: string;
export const btnSave: string;
export const btnCancel: string;
export const customTab: string;
export const bodyTab: string;
export const customIndicator: string;
export const titleRow: string;
export const btnBack: string;
export const btnImage: string;
export const customBoom: string;
export const customXelect: string;
export const customTitle: string;
